server {
  listen 80;
  server_name todo-list-api.2ao1.space;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  error_page 404 /index.html;
}
